services:
  web:
    build: ./stern-marzahn-website
    command: npm run start
    develop:
      watch: 
        - action: sync
          path: ./stern-marzahn-website
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    image: ghcr.io/kory291/stern-marzahn-website:latest
    pull_policy: always
    ports: 
      - "${FRONTEND_PORT-4200}:4200"
    restart: unless-stopped

  backend:
    image: ghcr.io/kory291/stern-marzahn-backend:latest
    build: ./stern-marzahn-backend
    develop:
      watch: 
        - action: sync
          path: ./stern-marzahn-backend
          target: /app
          ignore:
            - venv
            - __pycache__
            - .pytest_cache
        - action: rebuild
          path: pyproject.toml
    pull_policy: always
    ports: 
      - "${BACKEND_PORT-8000}:8000"
    restart: unless-stopped
