name: Build new images for Stern Marzahn Website

on:
    push: 
        branches: main

jobs:
    build: 
        runs-on: ubuntu:latest
        container: docker:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build images
              run: |
                docker build -f stern-marzahn-website/Dockerfile -t stern-marzahn-website:latest stern-marzahn-website
                docker build -f stern-marzahn-backend/Dockerfile -t stern-marzahn-backend:latest stern-marzahn-backend

            - name: Push images
              run: |
                echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin
                docker tag stern-marzahn-website:latest ghcr.io/kory291/stern-marzahn-website:latest
                docker tag stern-marzahn-backend:latest ghcr.io/kory291/stern-marzahn-backend:latest
                docker push ghcr.io/kory291/stern-marzahn-website:latest
                docker push ghcr.io/kory291/stern-marzahn-backend:latest
        permissions:
            contents: read
            packages: write
            id-token: write